### ISSUE TITLE
Discuss: Mission Statement for PDAP

### ISSUE THREAD

**Issue by jack-robs** [Police-Data-Accessibility-Project/planning#14]
What is your view of the PDAP's **Mission Statement**

If you have an idea of the Mission Statement, please contribute in this form below - succinct and measured is best. If you'd like to contribute dialogue towards what other Mission Statements have been suggested, keep it civil and facts-based.

Example Mission Statement idea:

```
(Have these two)
Mission Statement: PDAP's Mission Statement is......

Why I think this: 

(Suggested)
What will this Mission Statement stop us from doing:

How does this Mission Statement help us grow:
````

**Comment by dperegolise** [comment]
**Mission Statement:** I believe you guys got it right the first time, it should just be slightly reworded: 

_"PDAP exists to ingest, **aggregate, analyze, and publish** publicly accessible data regarding Law Enforcement records ~~. Using the data, citizens and communities can use the aggregate public data~~ **in order to empower citizens** to better understand the behaviors of local law enforcement and even individual police officers."_

**Why I think this:** Grassroots movements need a STRONG, SINGULAR direction. The above 'mission statement' is what attracted all of us here in the first place, and the best change would be effectively no change. 

**What will this Mission Statement stop us from doing:** This will stop us from 'scope creep', or in other words, expecting more out of this project than we should. Collecting, aggregating, analyzing, and publishing this data on a national level is already an enormous undertaking. Even more importantly, This will keep the mission statement strict and succinct, which will prevent all of our hundreds (soon maybe thousands) of moving pieces from flying in different directions. 

**How does this Mission Statement help us grow:** It is the same simple, succinct mission which attracted us all here in the first place. It is time to keep a closer eye on law enforcement officers.

**Comment by rainmana** [comment]
**Mission statement:** 
_Giving citizens an accessible view into the data that enables community-driven accountability for law enforcement and other public servants._

Why I think this:
It's broad enough to grow into other accountability projects but specific enough to be actionable in the present with the current scope.

**What will this Mission Statement stop us from doing:** 
This may be seen as exclusionary - as to we don't want to work with law enforcement and if that's the case, we'll need to determine to rectify that.

**How does this Mission Statement help us grow:**
This allows us to move into other areas where public servants act on our behalf and to where we want to keep them accountable if the project, funding, interest, etc. moves in that direction and shows what drives us. It contains parts of the organization's name and why we do what we do and how that can continue to grow - not just limited by law enforcement data.

**Comment by OscarVanL** [comment]
I agree with @dperegolise's interpretation. I think we should avoid using words like 'accountability' and instead emphasise that our focus is to publish data for others to use - it must be objective and not in any way interpreted or served with an opinion. 

At the moment, it's not viable for a non-technical person to do this, it is a complicated venture that will likely take many thousands of work-hours - this is what we should solve.

Based on the introductions I've seen, our skill-sets are overwhelmingly technical. There are more qualified people outside the group, academics and journalists for instance, who would do a better job interpreting and drawing conclusions from the data.

**Comment by nfrostdev** [comment]
> **Mission Statement:** I believe you guys got it right the first time, it should just be slightly reworded:
> 
> _"PDAP exists to ingest, **aggregate, analyze, and publish** publicly accessible data regarding Law Enforcement records ~. Using the data, citizens and communities can use the aggregate public data~ **in order to empower citizens** to better understand the behaviors of local law enforcement and even individual police officers."_
> 
> **Why I think this:** Grassroots movements need a STRONG, SINGULAR direction. The above 'mission statement' is what attracted all of us here in the first place, and the best change would be effectively no change.
> 
> **What will this Mission Statement stop us from doing:** This will stop us from 'scope creep', or in other words, expecting more out of this project than we should. Collecting, aggregating, analyzing, and publishing this data on a national level is already an enormous undertaking. Even more importantly, This will keep the mission statement strict and succinct, which will prevent all of our hundreds (soon maybe thousands) of moving pieces from flying in different directions.
> 
> **How does this Mission Statement help us grow:** It is the same simple, succinct mission which attracted us all here in the first place. It is time to keep a closer eye on law enforcement officers.

I'm really liking this so far, but I am uncertain if we need to include "and even individual police officers.", or the word "local" before "law enforcement".

Personally, I think it could just be narrowed down to your first portion:

_PDAP exists to ingest, aggregate, analyze, and publish publicly accessible data regarding Law Enforcement records._

This is me attempting to be completely unbiased here, maybe to an extreme degree. I believe that some minds may imply everything after what I have trimmed above could be an implication of intent with the data. I would like it to be very clear that we get data, organize it, make sure it is accurate, and publish it, **that's it.**

I'd love to hear other thoughts on this. I feel like I'm a bit paranoid.

**Comment by LJMcGregor** [comment]
I think @dperegolise has a great direction here. I love all of their reasoning.

Re: @OscarVanL and @nfrostdev's thoughts on objectivity/unbiased-ness: Having done some relatively serious community and editing on Wikipedia, I worry about neutrality actually derailing a grassroots effort like this one. The reason many people have been drawn to this project is because citizens are often dis-empowered w.r.t. police because _even though the data is public and accessible_, they do not individually have the means to find it, aggregate it, and analyze it. We can provide huge value here by tackling those pain points—but it is specifically with the higher goal/mission of empowering citizens to act on the data. While we don't do that final step, I believe we shouldn't leave the empowerment of citizens out of our mission because that's what gives our grassroots effort life and motivation.

A few small edits to @dperegolise's start:
- I think "ingest" doesn't mean anything other than "eating" to the **vast** majority of people, so we should leave it out. I believe we duo not need anything to replace it because (it's a writing-oriented detail, but) four action words is too many and people are accustomed to seeing threes. "Aggregate" by popular definition probably covers what we might have meant by "ingest".
- "publicly accessible" could become just "public", because pubic data is/should necessarily be accessible to the public.
- I think @nfrostdev is on to something with streamlining adjectives/explanation around law enforcement. "and even individual police officers" is an exciting and important detail about our project, but it doesn't need to be in our mission statement, because they are the local police. "local" is, I think, implied in "law enforcement" but I believe it's a valuable reminder about the problem we're tackling: local data is usually never published in any one standard way, and usually lives and dies on 10,000s of municipal servers. Our mission is necessarily local.

Proposed mission in light of the above small edits, and based on @dperegolise's reasoning:

> PDAP exists to aggregate, analyze, and publish public data regarding Law Enforcement records in order to empower citizens to better understand the behaviors of local law enforcement.

**Comment by jackfarzan** [comment]
Hi, I'm new here, which I think offers me a unique perspective to the in-progress mission statement. A mission statement requires you to make a clear impression of your goals as an organization in less time than an elevator pitch.

>PDAP exists to aggregate, analyze, and publish public data regarding Law Enforcement records in order to empower citizens to better understand the behaviors of local law enforcement.

This is a weak statement. What behaviors? Am I trying to understand how often cops take coffee breaks? Or am I trying to understand how often citizens have made complaints against them? As someone who has spent approximately 5 minutes on this repo, I should be able to answer that question, but I can't. I will decline from filling in the blanks because I've only spent 5 minutes here, but this statement needs to be more meaningful.

**Comment by dvaun** [comment]
We began our project with a rough draft that reads:

> Our mission is to enable a more transparent and empowered society by making law enforcement public records open source and easily accessible to the public.

Over the past week it's become well-known that our data will be distributed for analysis and research; whether the analysis and articles are written by ourselves or other organizations does not necessarily matter. What we can derive from this is that our data will be used to educate and empower the public — both citizens and agencies — on law enforcement activity in their communities. I agree with @LJMcGregor that the end result of the mission is an empowered public.

If we combine the statements:

> Our mission is to educate and empower citizens within their communities by aggregating, analyzing and publishing public law enforcement legal records and activities.

With our purpose being along the lines of this:

> By doing so, we would educate the public in lawn enforcement trends and activity and enable other organizations to easily perform analysis and communicate with law enforcement agencies directly with data in-hand.

**Why I think this:** We are here to make law enforcement data open-source and easily accessible for citizens to review and be informed on law enforcement practices and activities in their communities, and for research and analysis to be performed by other agencies.

PDAP will be an _educational_, and perhaps _literary_, organization due to the scope of our work. We should always strive to be non-partisan and strict with the data we collect and then make available online.

What are your thoughts?

**Comment by jackfarzan** [comment]
> We are here to make law enforcement data open-source and easily accessible for citizens to review and be informed on law enforcement practices and activities in their communities, and for research and analysis to be performed by other agencies.

You may not have meant it as a mission statement, but I think this would be a much better than what currently exists. It clearly states the immediate goal and why that goal is useful for others. If I make some adjustments:

> PDAP will consolidate public** law enforcement data in order to empower citizens to self-inform on law enforcement practices and activities in their communities, as well as for research and analysis by other agencies. 

_**It might also be prudent to specify that this data is American, not sure what the goals are in that regard._

**Why I think this:** 
From the present conversation, it is apparent that PDAP itself does not immediately seek to educate, it seeks to gather already available data and allow others to draw their own conclusions from it. One cannot educate solely based on the existence of data, rather enable others to draw their own conclusions. This should be clear in the mission statement.
