### ISSUE TITLE
Run `black` on all Python, set up a Python linter action

### ISSUE THREAD

**Issue by mcsaucy** [Police-Data-Accessibility-Project/planning#69]
Having a Python linter would help us maintain good code health. Before we (or immediately after) do that, we should hit everything with `black` once and manually tidy up what's necessary so we start out healthy.

If we want to use `black` more going forward, I'd be down for that, but I don't have a strong opinion.

**Comment by Astaltine** [comment]
Strong 👍 from me - I've used black for a while and it does a great job at making Python more readable, and saves developers and PR reviewers countless time by side-stepping the ever-present formatting-preference arguments. 

I think one of the last things that we'd want is for a potential contributor to get stopped at the door due to a bad experience with a PR that devolved into minutiae of formatting
